require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/MethodLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

Rubocop/DescribeClass:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
